#!/bin/bash

BARAKAFRITES_HOST=${BARAKAFRITES_HOST:-'172.17.42.1'}

cat <<EOF > /etc/nginx/conf.d/barakafrites_upstream.conf
upstream barakafrites {
    server $BARAKAFRITES_HOST:9292;
}
EOF

chmod 755 /swif/sites

/usr/sbin/nginx && tail -F /var/log/nginx/nginx.log
